#!/usr/bin/ruby

unless ARGV[0]
  puts 'Usage: np "the post title"'
  exit(-1)
end

title = ARGV.join ' '
date_prefix = Time.now.strftime("%Y-%m-%d")
postname = title.strip.downcase.gsub(/ /, '-')
post = "./_posts/#{date_prefix}-#{postname}.textile"
 
header = <<-END
---
layout: post
title: #{title}
---

h1. {{ page.title }}

p(meta). #{Time.now.strftime '%d %b %Y'} - Beijing

END
 
File.open(post, 'w') { |f| f << header }
system("mate", "-a", post)
